name: PR Review with Azure OpenAI (Alternative)

on:
  pull_request:
    types: [opened, synchronize, reopened]

# Minimal permissions needed
permissions:
  contents: read
  pull-requests: write

jobs:
  ai-review:
    runs-on: ubuntu-latest
    name: AI Code Review
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Azure OpenAI PR Review
        id: review
        uses: ./
        with:
          azure_openai_endpoint: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          azure_openai_api_key: ${{ secrets.AZURE_OPENAI_API_KEY }}
          azure_openai_deployment_name: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
          max_tokens: '1500'
          temperature: '0.1'
      
      - name: Create Review Comment
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          REVIEW_RESULT: ${{ steps.review.outputs.review_result }}
        run: |
          # Create comment using GitHub CLI
          if [ "${{ steps.review.outcome }}" = "success" ]; then
            # Parse the review result and create comment
            SCORE="${{ steps.review.outputs.score }}"
            APPROVED="${{ steps.review.outputs.approved }}"
            SUMMARY="${{ steps.review.outputs.summary }}"
            
            # Create comment body
            COMMENT_BODY="## 🤖 AI Code Review

          **Overall Score:** ${SCORE}/10
          **Status:** $(if [ "$APPROVED" = "true" ]; then echo "✅ Approved"; else echo "❌ Changes Requested"; fi)

          ### Summary
          $SUMMARY

          ---
          *Generated by Azure OpenAI PR Review Agent*"
            
            # Post comment using GitHub CLI
            echo "$COMMENT_BODY" | gh pr comment "$PR_NUMBER" --body-file -
            
            echo "✅ Review comment posted successfully"
          else
            # Post error comment
            gh pr comment "$PR_NUMBER" --body "## 🤖 AI Code Review

          ❌ **Error:** Could not complete the review due to a technical issue.

          Please check the action logs for more details.

          ---
          *Generated by Azure OpenAI PR Review Agent*"
            
            echo "❌ Posted error comment"
          fi
